// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLvuUCPbX85Om2z-gcmW3XHgfQPcFUds',
    appId: '1:1051876516870:web:ab1e17d6ad57cfb5a64f87',
    messagingSenderId: '1051876516870',
    projectId: 'networkchecker-67f04',
    authDomain: 'networkchecker-67f04.firebaseapp.com',
    storageBucket: 'networkchecker-67f04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXtRUe0PbH1S7LnGx-26iFVY0AsjmnLDw',
    appId: '1:1051876516870:android:e65fc55f34bd9443a64f87',
    messagingSenderId: '1051876516870',
    projectId: 'networkchecker-67f04',
    storageBucket: 'networkchecker-67f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxJj2Y95s82iJp2BLiCP0gtwivR7U_PE',
    appId: '1:1051876516870:ios:96d54f73e2d36be4a64f87',
    messagingSenderId: '1051876516870',
    projectId: 'networkchecker-67f04',
    storageBucket: 'networkchecker-67f04.firebasestorage.app',
    iosBundleId: 'com.ffsc2026.networkChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvxJj2Y95s82iJp2BLiCP0gtwivR7U_PE',
    appId: '1:1051876516870:ios:96d54f73e2d36be4a64f87',
    messagingSenderId: '1051876516870',
    projectId: 'networkchecker-67f04',
    storageBucket: 'networkchecker-67f04.firebasestorage.app',
    iosBundleId: 'com.ffsc2026.networkChecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADLvuUCPbX85Om2z-gcmW3XHgfQPcFUds',
    appId: '1:1051876516870:web:3121b5d0801a3a25a64f87',
    messagingSenderId: '1051876516870',
    projectId: 'networkchecker-67f04',
    authDomain: 'networkchecker-67f04.firebaseapp.com',
    storageBucket: 'networkchecker-67f04.firebasestorage.app',
  );
}
